export const theme = {
  dimmer: {
    main: 'rgba(0, 0, 0, 0.75)',
    medium: 'rgba(0, 0, 0, 0.5)',
    inverted: '',
    light: 'rgba(0, 0, 0, 0.13)',
  },
  primary: {
    light: 'rgba(255, 51, 102, 0.15)',
    medium: '#FF4F7B',
    main: '#FF3366',
    dark: '#FF1A53',
  },
  secondary: {
    light: '#FFFFFF',
    medium: '#FFFFFF',
    main: '#FCFCFC',
    dark: '#F9F9F9',
    semiDark: '#B6B6B6',
  },
  secondaryAlt: {
    light: '#2FD58F',
    main: '#14C855',
    dark: '#0EB64B',
    medium: '#797979',
  },
  background: {
    light: '#FFFFFF',
    main: '#F4F4F4',
    medium: '#E5E5E5',
    dark: '#F9F9F9',
    transparent: '#ffffff00',
    secondary: '#fefafc',
    badge: '#f28f2a',
    lightSecondary: '#FFECF0',
    highlightedGrey: '#F1F1F1',
    lightDark: '#292929',
  },
  surface: {
    light: '#FFFFFF',
    medium: '#F7F7F7',
    mediumAlt: '#EEEEEE',
    main: '#F9F9F9',
    dark: '#000000',
    blue: '#f9fcff',
  },
  border: {
    lightWithOpacity: 'rgba(255, 255, 255, 0.6)',
    light: '#FFFFFF',
    medium: '#EFEFEF',
    main: '#E5E5E5',
    dark: '#DADADA',
    secondary: '#ed93b1',
    darkblue: '#dae8f6',
    lightGrey: '#e5e5e5',
    lightRed: '#ff3366',
    grey: '#D8D8D8',
  },
  error: {
    light: '',
    main: 'red',
    dark: '#9f3a38',
    medium: '#EA3535',
  },
  warning: {
    light: '#FFFF00',
    main: '#FF9001',
    dark: '#FF8800',
  },
  info: {
    light: '',
    main: '#33B5E5',
    dark: '#0099CC',
  },
  onPrimary: {
    light: '#000000',
    main: '#FFFFFF',
    dark: '#FFFFFF',
  },
  onSecondary: {
    light: '',
    lightAlt: '#979797',
    medium: '#CFCFCF',
    main: '#FFFFFF',
    dark: '',
  },
  onBackground: {
    light: '#5C5C5C',
    lightAlt: '#B3B3B3',
    main: '#ECECEC',
    dark: '#FFFFFF',
  },
  onSurface: {
    light: '#000000',
    lightAlt: '#909090',
    medium: '#A0A0A0',
    mediumAlt: '#636363',
    main: '#000000',
    dark: '#ffffff',
    darkAlt: '#202020',
  },
  onError: {
    light: '',
    main: '',
    dark: '',
  },
  tabIndicator: {
    assigned: '#1476CC',
    enrolled: '#FF9001',
    progress: '#1476CC',
    overdue: '#FF3366',
    completed: '#14C855',
    certified: '#1476CC',
  },
  pieChart: {
    passed: '#FF3366',
    notStarted: '#FF5982',
    inProgress: '#FF7E9E',
    failed: '#FF9CB5',
    skipped: '#FFB0C4',
    noAssessment: '#FFCEDA',
  },
  banner: {
    draft: '#A0A0A0',
    cancelled: '#F82525',
    upcoming: '#1E97FF',
  },
  ecommerce: {
    course: '#9893FF',
    path: '#FFBC64',
  },
};
